#requires -Version 5.1
<#
Generated by SCE Editor for this project. It contains this machine's launcher path
and this project's client-only debug arguments.
#>
[CmdletBinding()]
param(
    [Parameter(Mandatory = $false)]
    [string] $ProjectRoot,

    [Parameter(Mandatory = $false)]
    [switch] $ResolveOnly,

    [Parameter(Mandatory = $false)]
    [switch] $DebugClient,

    [Parameter(Mandatory = $false)]
    [string[]] $ExtraArgs = @()
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

# Generated values are UTF-8 Base64 encoded so this script stays ASCII-safe for
# Windows PowerShell 5.1. Run with -ResolveOnly to print decoded launch values.
$ProjectRoot = ([System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String('RTovUHJvamVjdF9BSS9haV9jaGFqaWFuL0ZhaXJ5R1VJLVNDRS0yLjAvbmV3XzI2MDQwOQ==')))
$Executable = ([System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String('RDovUHJvZ3JhbUZpbGVzL+aYn+eBq+e8lui+keWZqDIv5pif54Gr57yW6L6R5ZmoIOWklue9kea1i+ivlS5leGU=')))
$WorkingDirectory = ([System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String('RDovUHJvZ3JhbUZpbGVzL+aYn+eBq+e8lui+keWZqDI=')))
$EditorRoot = ([System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String('RDovUHJvZ3JhbUZpbGVzL+aYn+eBq+e8lui+keWZqDIvdmVyc2lvbi0yMDAw')))
$Game = ([System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String('cF80cHdm')))
$EditorApiVersion = ([System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String('MjAwMA==')))
$LogsRoot = ([System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String('RDovUHJvZ3JhbUZpbGVzL+aYn+eBq+e8lui+keWZqDIvbG9ncw==')))
$Arguments = @(
    ([System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String('LWVudj1nYW1l'))),
    ([System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String('LWVkaXRvcl9zZXJ2ZXJfZGVidWc='))),
    ([System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String('LWNsaWVudF9vbmx5'))),
    ([System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String('LWVkaXRvcl9hcGlfdmVyc2lvbj0yMDAw'))),
    ([System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String('LWdhbWU9cF80cHdm'))),
    ([System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String('LW1hcF9raW5kPTA='))),
    ([System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String('LW1hcF9wYXRoPUU6L1Byb2plY3RfQUkvYWlfY2hhamlhbi9GYWlyeUdVSS1TQ0UtMi4wL25ld18yNjA0MDk='))),
    ([System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String('LXJ1bnRpbWVfbWNwX3BvcnQ9MTg3NjU=')))
)

if ([string]::IsNullOrWhiteSpace($WorkingDirectory)) {
    $WorkingDirectory = Split-Path $Executable -Parent
}
if ([string]::IsNullOrWhiteSpace($LogsRoot)) {
    $LogsRoot = Join-Path $WorkingDirectory "logs"
}

function ConvertTo-CommandLineArgument {
    param([Parameter(Mandatory = $true)][AllowEmptyString()][string] $Argument)
    if ($Argument.Length -eq 0) { return '""' }
    if ($Argument -notmatch '[\s"]') { return $Argument }
    return '"' + $Argument.Replace('"', '\"') + '"'
}

function Join-CommandLineArguments {
    param([Parameter(Mandatory = $true)][string[]] $Arguments)
    return (($Arguments | ForEach-Object { ConvertTo-CommandLineArgument $_ }) -join " ")
}

function Get-ArgumentValue {
    param(
        [Parameter(Mandatory = $true)][string[]] $Arguments,
        [Parameter(Mandatory = $true)][string] $Name
    )
    $Prefix = "-" + $Name + "="
    foreach ($Arg in $Arguments) {
        if ($Arg.StartsWith($Prefix, [System.StringComparison]::OrdinalIgnoreCase)) {
            return $Arg.Substring($Prefix.Length)
        }
    }
    return $null
}

function Get-DllDeploymentStatus {
    param(
        [Parameter(Mandatory = $true)][string] $Root,
        [Parameter(Mandatory = $true)][string] $Configuration,
        [Parameter(Mandatory = $true)][string] $TargetRelativePath
    )

    $Source = Join-Path $Root ("src\bin\{0}\net9.0\GameEntry.dll" -f $Configuration)
    $Target = Join-Path $Root $TargetRelativePath
    $SourceItem = Get-Item -LiteralPath $Source -ErrorAction SilentlyContinue
    $TargetItem = Get-Item -LiteralPath $Target -ErrorAction SilentlyContinue
    $NeedsDeploy = $false
    if ($null -ne $SourceItem -and $null -eq $TargetItem) {
        $NeedsDeploy = $true
    } elseif ($null -ne $SourceItem -and $null -ne $TargetItem) {
        $NeedsDeploy = ($SourceItem.LastWriteTimeUtc -gt $TargetItem.LastWriteTimeUtc) -or ($SourceItem.Length -ne $TargetItem.Length)
    }

    return [ordered]@{
        configuration = $Configuration
        source = $Source
        target = $Target
        sourceExists = $null -ne $SourceItem
        targetExists = $null -ne $TargetItem
        sourceLength = if ($null -ne $SourceItem) { $SourceItem.Length } else { $null }
        targetLength = if ($null -ne $TargetItem) { $TargetItem.Length } else { $null }
        sourceLastWriteTime = if ($null -ne $SourceItem) { $SourceItem.LastWriteTime.ToString("s") } else { $null }
        targetLastWriteTime = if ($null -ne $TargetItem) { $TargetItem.LastWriteTime.ToString("s") } else { $null }
        needsDeploy = $NeedsDeploy
    }
}

function Get-ProcessCreationTimeUtc {
    param($Process)
    if ($null -eq $Process -or $null -eq $Process.CreationDate) { return $null }
    if ($Process.CreationDate -is [DateTime]) {
        return ([DateTime]$Process.CreationDate).ToUniversalTime()
    }
    if ($Process.CreationDate -is [DateTimeOffset]) {
        return ([DateTimeOffset]$Process.CreationDate).UtcDateTime
    }
    try {
        return [System.Management.ManagementDateTimeConverter]::ToDateTime([string]$Process.CreationDate).ToUniversalTime()
    } catch {
        $Parsed = [DateTime]::MinValue
        if ([DateTime]::TryParse([string]$Process.CreationDate, [ref]$Parsed)) {
            return $Parsed.ToUniversalTime()
        }
    }
    return $null
}

function ConvertTo-ClientProcessInfo {
    param($Process)
    if ($null -eq $Process) { return $null }
    $CreationTimeUtc = Get-ProcessCreationTimeUtc $Process
    return [ordered]@{
        processId = [int]$Process.ProcessId
        parentProcessId = [int]$Process.ParentProcessId
        name = [string]$Process.Name
        executablePath = [string]$Process.ExecutablePath
        commandLine = [string]$Process.CommandLine
        creationTimeUtc = if ($null -ne $CreationTimeUtc) { $CreationTimeUtc.ToString("o") } else { $null }
    }
}

function Find-SceClientProcess {
    param(
        [Parameter(Mandatory = $true)][int] $LauncherProcessId,
        [Parameter(Mandatory = $true)][string] $Root,
        [Parameter(Mandatory = $true)][int] $RuntimePort,
        [Parameter(Mandatory = $true)][DateTime] $StartedAfterUtc
    )

    $NormalizedRoot = $Root.Replace('\', '/')
    $MinimumCreationTimeUtc = $StartedAfterUtc.ToUniversalTime().AddSeconds(-2)
    $Deadline = [DateTime]::UtcNow.AddSeconds(8)
    do {
        $AllProcesses = @(Get-CimInstance -ClassName Win32_Process -ErrorAction SilentlyContinue)
        $Candidates = @($AllProcesses | Where-Object {
            $Name = [string]$_.Name
            $CommandLine = [string]$_.CommandLine
            $NormalizedCommandLine = $CommandLine.Replace('\', '/')
            $IsSceProcess = $Name -ieq "sce" -or $Name -ieq "sce.exe"
            $IsLauncherProcess = [int]$_.ProcessId -eq $LauncherProcessId
            $IsDirectChild = ([int]$_.ParentProcessId -eq $LauncherProcessId) -and $IsSceProcess
            $IsClientOnly = $CommandLine -match "-client_only"
            $MatchesProject = $NormalizedCommandLine.IndexOf($NormalizedRoot, [System.StringComparison]::OrdinalIgnoreCase) -ge 0
            $MatchesRuntimePort = $CommandLine -match ("-runtime_mcp_port=" + [regex]::Escape([string]$RuntimePort))
            $CreationTimeUtc = Get-ProcessCreationTimeUtc $_
            $IsNewFallbackProcess = $null -ne $CreationTimeUtc -and $CreationTimeUtc -ge $MinimumCreationTimeUtc
            $IsDirectChild -or ((-not $IsLauncherProcess) -and $IsSceProcess -and $IsClientOnly -and $IsNewFallbackProcess -and ($MatchesProject -or $MatchesRuntimePort))
        })

        if ($Candidates.Count -gt 0) {
            $DirectChildren = @($Candidates | Where-Object { [int]$_.ParentProcessId -eq $LauncherProcessId })
            if ($DirectChildren.Count -gt 0) {
                return ConvertTo-ClientProcessInfo $DirectChildren[0]
            }
            return ConvertTo-ClientProcessInfo $Candidates[0]
        }

        Start-Sleep -Milliseconds 250
    } while ([DateTime]::UtcNow -lt $Deadline)

    return $null
}

if ($DebugClient) {
    $Arguments += "-debug"
}
foreach ($arg in $ExtraArgs) {
    if (-not [string]::IsNullOrWhiteSpace($arg)) {
        $Arguments += $arg
    }
}

$RuntimeMcpPort = 18765
$RuntimeMcpPortText = Get-ArgumentValue -Arguments $Arguments -Name "runtime_mcp_port"
if (-not [string]::IsNullOrWhiteSpace($RuntimeMcpPortText)) {
    $ParsedRuntimeMcpPort = 0
    if ([int]::TryParse($RuntimeMcpPortText, [ref]$ParsedRuntimeMcpPort) -and $ParsedRuntimeMcpPort -gt 0 -and $ParsedRuntimeMcpPort -le 65535) {
        $RuntimeMcpPort = $ParsedRuntimeMcpPort
    }
}

$ArgumentLine = Join-CommandLineArguments -Arguments $Arguments
$AppBundleDeployment = [ordered]@{
    server = Get-DllDeploymentStatus -Root $ProjectRoot -Configuration "Server-Debug" -TargetRelativePath "AppBundle\managed\GameEntry.dll"
    client = Get-DllDeploymentStatus -Root $ProjectRoot -Configuration "Client-Debug" -TargetRelativePath "ui\AppBundle\managed\GameEntry.dll"
}
$Result = [ordered]@{
    projectRoot = $ProjectRoot
    editorRoot = $EditorRoot
    executable = $Executable
    executableKind = "generated-script"
    workingDirectory = $WorkingDirectory
    game = $Game
    editorApiVersion = $EditorApiVersion
    arguments = $Arguments
    argumentLine = $ArgumentLine
    logsRoot = $LogsRoot
    runtimeMcp = [ordered]@{
        host = "127.0.0.1"
        port = $RuntimeMcpPort
        endpoint = "tcp://127.0.0.1:$RuntimeMcpPort"
        protocol = "sce-runtime-tcp"
        bridgeTool = "runtime_call_tool"
    }
    appBundleDeployment = $AppBundleDeployment
}

if ($ResolveOnly) {
    $Result.started = $false
    $Result | ConvertTo-Json -Depth 5
    return
}

if (-not (Test-Path -LiteralPath $Executable -PathType Leaf)) {
    throw "Client-only debug executable does not exist: $Executable. Open the project once in SCE Editor to refresh this script."
}

$StartInfo = New-Object System.Diagnostics.ProcessStartInfo
$StartInfo.FileName = $Executable
$StartInfo.WorkingDirectory = $WorkingDirectory
$StartInfo.Arguments = $ArgumentLine
$StartInfo.UseShellExecute = $false

$LaunchStartedUtc = [DateTime]::UtcNow
$Process = [System.Diagnostics.Process]::Start($StartInfo)
if ($null -eq $Process) {
    throw "Failed to start SCE client-only debug process."
}

$Result.started = $true
$Result.processId = $Process.Id
$Result.launcherProcessId = $Process.Id
$ClientProcess = Find-SceClientProcess -LauncherProcessId $Process.Id -Root $ProjectRoot -RuntimePort $RuntimeMcpPort -StartedAfterUtc $LaunchStartedUtc
$Result.clientProcess = $ClientProcess
$Result.clientProcessId = if ($null -ne $ClientProcess) { $ClientProcess.processId } else { $null }
$Result | ConvertTo-Json -Depth 5
