// <auto-generated>
// Generated projection of authoritative GameData source.
// Edit editor/data JSON (or use data_* MCP) for json-backed tables, or define data in code via new GameDataXxx(...).
// Do not treat mutation of ScopeData.GameDataXxx.*.Data as a static authoring pattern.
// Do not edit this file manually. Your changes will be lost.
// </auto-generated>
using GameData;
namespace GameEntry.DataGenerated.GameEntry.ScopeData.GameDataScene;
internal static class new_scene
{
    private static void Root()
    {
        var id = "$GameEntry.ScopeData.GameDataScene.new_scene.Root";
        var template = "$gamesparkcore.ScopeDataTemplate.GameDataScene.SceneTemplate.Root";
        var instance = IGameData.Create<global::GameCore.SceneSystem.Data.GameDataScene>(template, id);
        if (instance == null)
        {
            Game.Logger.LogWarning($"{template}不存在或不是global::GameCore.SceneSystem.Data.GameDataScene类型");
            return;
        }
        instance.HostedSceneTag = "new_scene";
        instance.Name = "默认场景";
        var size1 = instance.Size;
        {
            size1.X = 4096f;
            size1.Y = 4096f;
        }
        instance.Size = size1;
    }

    internal static void OnRegisterGameData()
    {
        Root();
    }
}
