// <auto-generated>
// Version: 0.0.12
// Timestamp: 1783845544
// Generated projection of authoritative GameData source.
// Edit editor/data JSON (or use data_* MCP) for json-backed tables, or define data in code via new GameDataXxx(...).
// Do not treat mutation of ScopeData.GameDataXxx.*.Data as a static authoring pattern.
// Do not edit this file manually. Your changes will be lost.
// </auto-generated>
using GameData;
namespace GameEntry.ScopeData
{
    public static partial class GameDataGameMode
    {
        /// <summary>
        /// Generated initialization code: <see cref="GameEntry.DataGenerated.GameEntry.ScopeData.GameDataGameMode.MapGameMode.Root"/>.
        /// </summary>
        public static readonly GameLink<global::GameCore.GameSystem.Data.GameDataGameMode, global::GameCore.GameSystem.Data.GameDataGameMode> MapGameMode = new("$GameEntry.ScopeData.GameDataGameMode.MapGameMode.Root");
    }
    public static partial class GameDataPlayerSettings
    {
        /// <summary>
        /// Generated initialization code: <see cref="GameEntry.DataGenerated.GameEntry.ScopeData.GameDataPlayerSettings.PlayerSettings.Root"/>.
        /// </summary>
        public static readonly GameLink<global::GameCore.PlayerAndUsers.Data.GameDataPlayerSettings, global::GameCore.PlayerAndUsers.Data.GameDataPlayerSettings> PlayerSettings = new("$GameEntry.ScopeData.GameDataPlayerSettings.PlayerSettings.Root");
    }
    public static partial class GameDataScene
    {
        /// <summary>
        /// Generated initialization code: <see cref="GameEntry.DataGenerated.GameEntry.ScopeData.GameDataScene.new_scene.Root"/>.
        /// </summary>
        public static readonly GameLink<global::GameCore.SceneSystem.Data.GameDataScene, global::GameCore.SceneSystem.Data.GameDataScene> new_scene = new("$GameEntry.ScopeData.GameDataScene.new_scene.Root");
    }
}

namespace GameEntry
{
    internal class ScopeDataLoader : IGameClass
    {
        public static void OnRegisterGameClass()
        {
            Game.OnGameDataInitialization += OnGameDataInitialization;
        }

        private static void OnGameDataInitialization()
        {
            DataGenerated.GameEntry.ScopeData.GameDataGameMode.MapGameMode.OnRegisterGameData();
            DataGenerated.GameEntry.ScopeData.GameDataPlayerSettings.PlayerSettings.OnRegisterGameData();
            DataGenerated.GameEntry.ScopeData.GameDataScene.new_scene.OnRegisterGameData();
        }
    }
}
