// <auto-generated>
// Generated projection of authoritative GameData source.
// Edit editor/data JSON (or use data_* MCP) for json-backed tables, or define data in code via new GameDataXxx(...).
// Do not treat mutation of ScopeData.GameDataXxx.*.Data as a static authoring pattern.
// Do not edit this file manually. Your changes will be lost.
// </auto-generated>
using GameData;
namespace GameEntry.DataGenerated.GameEntry.ScopeData.GameDataGameMode;
internal static class MapGameMode
{
    private static void Root()
    {
        var id = "$GameEntry.ScopeData.GameDataGameMode.MapGameMode.Root";
        var instance = new global::GameCore.GameSystem.Data.GameDataGameMode(new(id))
        {
            DefaultScene = new GameLink<global::GameCore.SceneSystem.Data.GameDataScene, global::GameCore.SceneSystem.Data.GameDataScene>("$GameEntry.ScopeData.GameDataScene.new_scene.Root"),
            DisplayInfo = new GameLink<global::GameCore.GameSystem.Data.GameDataRule, global::GameCore.DisplayInfo.Data.GameDataRuleDisplayInfo>("DefaultDisplayInfo" /*$gamesparkcore.ScopeData.GameDataRule.DefaultDisplayInfo.Root*/),
            ExperienceGrant = new GameLink<global::GameCore.GameSystem.Data.GameDataRule, global::GameCore.Leveling.Data.GameDataRuleExperienceGrant>("DefaultExperienceGrant" /*$gamesparkcore.ScopeData.GameDataRule.DefaultExperienceGrant.Root*/),
            Gameplay = new GameLink<global::GameCore.GameSystem.Data.GameDataGameplay, global::GameCore.GameSystem.Data.GameDataGameplay>("Default" /*$gamesparkcore.ScopeData.GameDataGameplay.Default.Root*/),
            GameUI = new GameLink<global::GameUI.Data.GameDataGameUI, global::GameUI.Data.GameDataGameUI>("$gamesparkcore.ScopeData.GameDataGameUI.Default.Root"),
            Name = "当前地图游戏模式",
            PlayerSettings = new GameLink<global::GameCore.PlayerAndUsers.Data.GameDataPlayerSettings, global::GameCore.PlayerAndUsers.Data.GameDataPlayerSettings>("$GameEntry.ScopeData.GameDataPlayerSettings.PlayerSettings.Root"),
            SceneList = [new GameLink<global::GameCore.SceneSystem.Data.GameDataScene, global::GameCore.SceneSystem.Data.GameDataScene>("$GameEntry.ScopeData.GameDataScene.new_scene.Root")],
        };
    }

    internal static void OnRegisterGameData()
    {
        Root();
    }
}
